name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  EPP_CLIENT_ID: ${{secrets.EPP_CLIENT_ID}}
  EPP_CLIENT_PW: ${{secrets.EPP_CLIENT_PW}}
  BILLING_CURRENCY: USD
  PREMIUM_COST: 41.41
  TEST_TLD: smoketestcnic
  COVERAGE_THRESHOLD: 75

jobs:
  Test:
    runs-on: ubuntu-latest
    container: gbxyz/ubuntu-latest-php-82-openswoole:main
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: apt-get install -qqq php-pcov

      - name: run composer install
        run: composer install --dev

      - name: linter
        run: |
          find . -name "*.php" -not -path "*/vendor/*" -print0 | xargs --null --max-args=1 --max-procs="$(cat /proc/cpuinfo | grep ^processor | wc -l)" php --syntax-check > /dev/null

      - name: pest
        run: vendor/bin/pest --no-progress --coverage --coverage-text

      - name: coverage check
        run: vendor/bin/coverage-check clover.xml $COVERAGE_THRESHOLD
