name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '55 5 * * *'
  workflow_dispatch:

env:
  EPP_CLIENT1_ID: ${{secrets.EPP_CLIENT1_ID}}
  EPP_CLIENT1_PW: ${{secrets.EPP_CLIENT1_PW}}
  EPP_CLIENT2_ID: ${{secrets.EPP_CLIENT2_ID}}
  EPP_CLIENT2_PW: ${{secrets.EPP_CLIENT2_PW}}
  COVERAGE_THRESHOLD: 85

jobs:
  Test:
    runs-on: ubuntu-latest
    container: gbxyz/ubuntu-latest-php-82-openswoole:main
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: apt-get install -qqq php-pcov nodejs

      - name: run composer install
        run: composer install --dev

      - name: linter
        run: |
          find . -name "*.php" -not -path "*/vendor/*" -print0 | xargs --null --max-args=1 --max-procs="$(cat /proc/cpuinfo | grep ^processor | wc -l)" php --syntax-check > /dev/null

      - name: pest
        run: vendor/bin/pest --no-progress --coverage --coverage-text

      - name: coverage check
        run: vendor/bin/coverage-check clover.xml $COVERAGE_THRESHOLD

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
